
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$_PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "--",
        "python3",
        "manage.py",
        "migrate",
      ]
  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$_PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${_PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "--",
        "python3",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

substitutions:
  _INSTANCE_NAME: data-acid-db
  _REGION: europe-southwest1
  _SERVICE_NAME: data-acid-service


images:
  - "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}"
