# Generated by Django 4.2.6 on 2023-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_leadsform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsform',
            name='salary_range',
            field=models.CharField(max_length=100),
        ),
    ]
